### ISSUE TITLE
When running example sphere_sliding.py , an error occurred

### ISSUE THREAD

**Issue by cloneorcopy** [Yihao-Shi/GeoTaichi#1]
Thank you for your great work! I just try to run the demmp example (sphere_sliding.py), but iI got some trouble .The trackback was as follow : 

~~~
Exception has occurred: AttributeError
'LinearModel' object has no attribute 'null_model'
  File "E:\EX_library\GeoTaichi-main\src\mpdem\ContactManager.py", line 94, in add_contact_property
    if self.physpp.null_model is True and self.physpw.null_model is True:
  File "E:\EX_library\GeoTaichi-main\src\mpdem\mainDEMPM.py", line 140, in add_property
    self.contactor.add_contact_property(self.sims, DEMmaterial, MPMmaterial, property, dType)
  File "E:\EX_library\GeoTaichi-main\sphere_sliding.py", line 186, in <module>
    dempm.add_property(DEMmaterial=0,
AttributeError: 'LinearModel' object has no attribute 'null_model'
~~~

I think maybe there was something wrong with ContactModel. Noted that  all of ContactModes have a property named *null_mode*,  so maybe null_model in ContactManager.py means null_mode. I am not sure about it.

**Comment by Yihao-Shi** [comment]
Please download the latest version --commit d33ed83. I can run it successfully on my computer. Please contact us if you have any questions.
