### ISSUE TITLE
Installation and use of geotaichi

### ISSUE THREAD

**Issue by MINE0126** [Yihao-Shi/GeoTaichi#10]
Thank you for sharing such a great software package. Can this software package be used on the Windows platform? Why can't it be "imported" after installation? Thanks for your reply.
![image](https://github.com/Yihao-Shi/GeoTaichi/assets/107633173/7430722d-8874-4ec3-b3df-0732f6feb3ce)

**Comment by Yihao-Shi** [comment]
Our code is suitable for both Windows and Linux systems. This problem may be attributed to the incorrect Python path. If you find difficult to install, you can also type the following command in the terminal.
`
pip install geotaichi==0.2.0
`
