### ISSUE TITLE
GeoTaichi doesn't run -- pynvml and UTF-8 formatting conflicts for modern versions of CUDA (12+) / NVIDIA Drivers (550+)

### ISSUE THREAD

**Issue by JustinBonus** [Yihao-Shi/GeoTaichi#12]
**Problem:**

Package is not working with newer versions of CUDA/NVIDIA drivers due to (most likely) conflict of supporting libraries (pynvml) defaulting to a recent version (11.5+) while GeoTaichi tends to be conservative by selecting older versions of various other libraries (e.g. python3=3.8.0, taichi==1.6.0) which may lead to compatibility issues.

The pynvml library has a known issue concerning compatibility with certain NVIDIA drivers, OS, etc., for utf-8 encoding (the default for Python3 according to PEP standards). 

This seems to be primarily an issue in pynvml 11.5+, as of April - July 2024 (may be fixed in the future). See related issue at:
https://github.com/wandb/wandb/issues/7168 

Typically shows up as an error when running python packages reliant on it. Typically errors look like:
pynvml/pynvml.py", line 1962, in wrapper
    return res.decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf8 in position 0: invalid start byte

Above is what occurs for the Newtonian Fluid Column Collapse example (yet to test other examples for this error, but likely applies to all for affected systems).

**System and Reproducibility:**

Below is information regarding my system for reproducibility.

$ uname -a

Linux 5.15.146.1-microsoft-standard-WSL2 x86_64 x86_64 x86_64 GNU/Linux

$ nvidia-smi

+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 555.52.01              Driver Version: 555.99         CUDA Version: 12.5     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 4060 Ti     On  |   00000000:01:00.0  On |                  N/A |
|  0%   44C    P5             28W /  165W |    3260MiB /  16380MiB |      1%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A       619      G   /Xwayland                                   N/A      |
+-----------------------------------------------------------------------------------------+

$ python3 --version

Python 3.8.0

$ python3 -m pip list 

Package           Version
----------------- -------
astunparse        1.6.3
colorama          0.4.6
dill              0.3.8
geotaichi         0.2.4
imageio           2.34.2
markdown-it-py    3.0.0
mdurl             0.1.2
numpy             1.23.5
pillow            10.4.0
pip               24.1.2
pkg_resources     0.0.0
psutil            6.0.0
pybind11          2.13.1
Pygments          2.18.0
pynvml            11.5.3
rich              13.7.1
Rtree             1.3.0
scipy             1.10.1
setuptools        39.0.1
Shapely           1.8.0
six               1.16.0
taichi            1.6.0
trimesh           3.20.1
typing_extensions 4.12.2
wheel             0.43.0

Error is produced by running the following from the GeoTaichi top-level folder:
$ ti example/mpm/ColumnCollapse/NewtonianFluid.py
as well as:
$ python3 example/mpm/ColumnCollapse/NewtonianFluid.py

**Proposal:**

I propose downgrading pynvml to 11.4.1+ unless there is a compelling reason to the contrary.  

This may be manually down by a user with an existing install by using:
$ python3 -m pip install --upgrade pynvml==11.4.1
Collecting pynvml==11.4.1
  Downloading pynvml-11.4.1-py3-none-any.whl.metadata (7.7 kB)
Downloading pynvml-11.4.1-py3-none-any.whl (46 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 47.0/47.0 kB 1.7 MB/s eta 0:00:00
Installing collected packages: pynvml
  Attempting uninstall: pynvml
    Found existing installation: pynvml 11.5.3
    Uninstalling pynvml-11.5.3:
      Successfully uninstalled pynvml-11.5.3
Successfully installed pynvml-11.4.1

I am submitting a pull-request which edits the requirements.txt to use pynvml==11.4.1 to prevent the issue for users installing fresh. I will link back to this issue in it to help track down future issues if this eventually needs to be reverted to use a newer version of pynvml when they fix the underlying bug.

**Comment by Yihao-Shi** [comment]
Thanks  for your kindly reminder. But I have not found this issue in my system, of course, this may be resulted from various runtime environment. 

my pynvml version is 11.5.0:
```
pip list
>>>  pynvml                        11.5.0
```
and my cuda version is listed below:
```
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:2B:00.0  On |                  N/A |
| 30%   52C    P8    18W / 220W |   1019MiB /  7975MiB |     11%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

```

Anyway, thanks for your pointing out this problem. I will merge your pr into the main program.
