### ISSUE TITLE
geostudio can not be found！Why?

### ISSUE THREAD

**Issue by chenling669** [Yihao-Shi/GeoTaichi#14]
I want to run your GeoStudio example file, but I can't find GeoStudio. I first installed GeoStudio using Pip, but it still doesn't work. We spent a lot of effort to find it, and found that **there is a GeoStudio in your GitHub code, which is different from the code installed by Pip.** We hope you can modify it or make a statement

**Comment by Yihao-Shi** [comment]
Could you tell me which script in the [example folder](https://github.com/Yihao-Shi/GeoTaichi/tree/main/example) using GeoStudio. We do not have any examples named GeoStudio. Or could you please provide error message in log file to me?

**Comment by chenling669** [comment]
> Could you tell me which script in the [example folder](https://github.com/Yihao-Shi/GeoTaichi/tree/main/example) using GeoStudio. We do not have any examples named GeoStudio. Or could you please provide error message in log file to me?

OK，it is geostudio.It is your expression pip install geostudio

**Comment by Yihao-Shi** [comment]
in which python files I use expression `pip install geostudio`? I can't find it.

**Comment by chenling669** [comment]
![image](https://github.com/user-attachments/assets/fb528a30-9d0e-47ec-83e1-d513f8bf31fc)
Could you compare the geotaichi found in site-packages obtained from pip install geotaichi with the geotaichi code displayed on GitHub? Both versions are authored by Yihao-Shi.
