### ISSUE TITLE
ValueError: attempted relative import beyond top-level package

### ISSUE THREAD

**Issue by joeyandu** [Yihao-Shi/GeoTaichi#18]
Dear Yihao,

thank you for the great work!

I am a beginner in programming. I just downloaded the code and tried to run some examples, but I encountered this prompt. I haven't modified any code. Can you tell me why this is happening?

  File "/.../GeoTaichi/example/mpm/ColumnCollapse/bunny.py", line 4, in <module>
    from geotaichi import *
  File "/.../local/lib/python3.8/site-packages/geotaichi/__init__.py", line 11, in <module>
    from ..src import *
ValueError: attempted relative import beyond top-level package

Best regards,
Ray

**Comment by Yihao-Shi** [comment]
hello Ray, it seems there are some errors when install geotaichi from pypi. It is recommanded to install geotaichi from source code. Thanks.
