### ISSUE TITLE
Setting a tilted boundary in DEMPM

### ISSUE THREAD

**Issue by leyiuu** [Yihao-Shi/GeoTaichi#23]
Hi,

I am currently working with DEMPM, and I want to define a boundary where the lowest point is at [1, 1, 1], the region size is [0.2, 0.2, 0.2], and it is tilted at a 30° angle relative to the x-axis. However, it seems that the MPM boundary condition can only be set to a horizontal cubic region, such as [1, 1.2], [1, 1.2], [1, 1.2]. I would like to know if there is an appropriate way to create a tilted boundary for my case.

Thank you for your help!

Best regards,
Leyiuu

**Comment by Yihao-Shi** [comment]
you can add a keyword (zdirection) in the region dictionary to set your region's orientation, here is a example:
```
region={
                            "Name": "region1",
                            "Type": "Rectangle",
                            "BoundingBoxPoint": ti.Vector([0.00, 0.00, 0.00]),
                            "BoundingBoxSize": ti.Vector([0.2, 0.05, 0.1]),
                            "zdirection": ti.Vector([1., 0., 1.])    # change the orientation
                      }
```
