### ISSUE TITLE
Unexpected behavior occurs when running 2 mpm in one file

### ISSUE THREAD

**Issue by Mathias0** [Yihao-Shi/GeoTaichi#5]
First of all, thank you very much for developping this powerful GeoTaichi!!

I find the codes well structured and I want to write a 2-grid MPM code using GeoTaichi. So I began from defining 2 MPM in one file. If everything goes well, I can then define how the fields in 2 MPM interacts with each other (known as 2-grid MPM).

When I try to run 2 MPM in one file, I observed one weird behavior. In the code I shared, I define 2 MPM and no interaction between them is defined. It is about the dam-breaking of same kind of Newtonian fluid initially occupying 2 symmetric rectangle region. It is expected that their behavior is also symmetric.

As written in the [code](https://github.com/Yihao-Shi/GeoTaichi/files/15278677/twoMPM.txt) I shared, if the order of the last 2 lines is 

mpm2.run()
mpm1.run()

then everything goes well, the dam-break behavior being symmetric.

However, when the order is changed like this:

mpm1.run()
mpm2.run()

the behavior is no longer symmetric, which is unexpected and undesired. 

I know the way I use GeoTaichi is not the common way or the normal way. The problem I occured would almost never be occurred for those who use GeoTaichi in a normal way. But I just really want to find out what is causing this so that I could find a way to fix it or avoid it. (When I tried further coupling the 2 MPM, this problem is always happening and cannot be solved by simply change the ordes)

Are there some infomations shared by the two instances of MPM() ?

(When I tried further coupling the 2 MPM, this problem is always happening and cannot be solved by simply change the order. The way I tried to further coupling is like expanding the run() into:

...

while current_time<time:

     ...

     mpm1.solver.engine.compute_nodal_kinematic(mpm1.solver.sims, mpm1.scene)
     mpm2.solver.engine.compute_nodal_kinematic(mpm2.solver.sims, mpm2.scene)

     exchange_momentum(mpm1.scene.node, mpm2.scene.node)

     mpm1.solver.engine.compute_grid_velcity(mpm1.solver.sims, mpm1.scene)
     mpm2.solver.engine.compute_grid_velcity(mpm2.solver.sims, mpm2.scene)
    
     mpm1.solver.engine.apply_kinematic_constraints(mpm1.solver.sims, mpm1.scene)
     mpm2.solver.engine.apply_kinematic_constraints(mpm2.solver.sims, mpm2.scene)

     ...

)
(The background where I am applying this kind of coupling is simulating sand released in water.)

**Comment by Yihao-Shi** [comment]
hello [Mathias0](https://github.com/Mathias0), sorry for late reply. We have correct this issue, please download the latest version [1e4c9a3](https://github.com/Yihao-Shi/GeoTaichi/commit/1e4c9a3caf255ef88859f187b968d9ac95b30427)
