### ISSUE TITLE
Quick questions about MPM implementation

### ISSUE THREAD

**Issue by ZenanH** [Yihao-Shi/GeoTaichi#6]
Hi, 👋

congratulations of the paper and thanks for you nice code!

I still have several questions about the "pure" MPM implementation:

- how do you solve the race-condition problem during `p2g` process? By naive atomic lock?

- the second maybe relates to the first question, you are looping on particles or grid nodes?

- The GIMP in the code is `uGIMP` or `cpGIMP`?

- how do you set the launch configuration when you run the kernel functions on the GPU? E.g., hard coding as 256, 512 or something like that?

Best,

Zenan

**Comment by Yihao-Shi** [comment]
hello Zenan, thanks for your interest in our work!
1. yes, we solve race-condition problem using atomic lock. We have tried other advanced strategies, such as domain decomposition and particle list, we do not observe significant performance improvement in our code. For simplicity, we use naive atomic lock
2. we are looping on particles
3. GIMP is uGIMP. the areas of particles are undeformed during simulation
4. Taichi language can automatically handle this problem in general. But I can also specify the number of threads per block when necessary, like in [PrefixSum.py](https://github.com/Yihao-Shi/GeoTaichi/blob/main/src/utils/PrefixSum.py)

**Comment by Yihao-Shi** [comment]
We find that Compute Shape Function takes the most of the computational time (about 35%)

**Comment by Yihao-Shi** [comment]
> > We find that Compute Shape Function takes the most of the computational time (about 35%)
> 
> With standard MPM (linear basis function) or GIMP? Or maybe both?

Only for GIMP. For linear function, computing constitutive model becomes the bottleneck in the simulation.

In the process of computing shape function, there are a lot of if-else operations. so the warp divergence is unavoidable and it may significantly reduce the efficiency of GPU. 

It is my own opinion, as there are no references available to support this idea.
