### ISSUE TITLE
DPmaterial 模型修改

### ISSUE THREAD

**Issue by gongyuuhi** [Yihao-Shi/GeoTaichi#8]
您好，非常感谢您的代码使我在学习mpm的路上少了很多绊脚石！

我想修改或添加DPmaterial中的模型为三棱柱，在此基础上用于模拟一些边坡稳定问题，也就是把region中的"Rectangle"改为"TrianglarPrism",但是会输出错误，请问目前mpm代码是不支持除了rectangle以外的模型建立吗？
注意到有这段代码
![image](https://github.com/Yihao-Shi/GeoTaichi/assets/82460240/ca1f2a03-238f-45f1-9270-d139f246d401)

**Comment by Yihao-Shi** [comment]
mpm可以生成三角形模型，但是对于任意形状的mpm，比较难计算初始应力场，因此如果你需要生成初始应力场的话，需要根据你的形状修改kernel_apply_gravity_field_这个函数

**Comment by gongyuuhi** [comment]
好的了解，感谢您的回复！
